---
  - name: Get major version
    shell: cat /opt/couchbase/VERSION.txt | cut -d '.' -f1
    register: cb_major_version

  - name: Wait for Admin service
    wait_for:
      port: "{{ couchbase_admin_port }}"
      delay: 2

  - name: Initialize additional nodes
    shell: "{{ couchbase_bin_path }}/couchbase-cli node-init -c {{ ansible_fqdn }}:{{ couchbase_admin_port }} --user={{ couchbase_admin }} --password={{ couchbase_password }} --cluster-init-username={{ couchbase_admin }} --node-init-hostname={{ ansible_fqdn }} --node-init-data-path={{ couchbase_data_path }} --node-init-index-path={{ couchbase_index_path }}"
    when: cb_major_version['stdout'] != "2"
