---
  - name: Get major version
    shell: cat /opt/couchbase/VERSION.txt | cut -d '.' -f1
    register: cb_major_version

  - name: Join additional cluster nodes (version == 4)
    shell: "{{ couchbase_bin_path }}/couchbase-cli server-add -c {{ couchbase_primary_node }}:{{ couchbase_admin_port }} --user={{ couchbase_admin }} --password={{ couchbase_password }} --server-add={{hostvars[item[0]]['inventory_hostname']}}:{{ couchbase_admin_port }} --server-add-username={{ couchbase_admin }} --server-add-password={{ couchbase_password }}"
    with_items: "{{ groups['additional'] }}"
    when: cb_major_version['stdout'] != "4"

  - name: Join additional cluster nodes (version >= 4)
    shell: "{{ couchbase_bin_path }}/couchbase-cli server-add -c {{ couchbase_primary_node }}:{{ couchbase_admin_port }} --user={{ couchbase_admin }} --password={{ couchbase_password }} --server-add={{hostvars[[item][0]]['inventory_hostname']}}:{{ couchbase_admin_port }} --server-add-username={{ couchbase_admin }} --server-add-password={{ couchbase_password }} --services={{hostvars[[item][0]]['couchbase_node_services']}}"
    with_items: "{{ groups['additional'] }}"
    when: cb_major_version['stdout'] >= "4"

  - name: Rebalance cluster
    shell: "{{ couchbase_bin_path }}/couchbase-cli rebalance -c {{ couchbase_primary_node }}:{{ couchbase_admin_port }} --user={{ couchbase_admin }} --password={{ couchbase_password }}"
