---
  - name: Get major version
    shell: cat /opt/couchbase/VERSION.txt | cut -d '.' -f1
    register: couchbase_major_version

  # Admin port is hard coded in services
  - name: Wait for Admin service
    wait_for:
      port: 8091
      delay: 2

  - name: Initialize nodes
    shell: "/opt/couchbase/bin/couchbase-cli node-init -c {{ ansible_fqdn }}:8091 --user={{ couchbase_admin_username }} --password={{ couchbase_admin_password }} --cluster-init-username={{ couchbase_admin_username }} --node-init-hostname={{ ansible_fqdn }} --node-init-data-path={{ couchbase_data_path }} --node-init-index-path={{ couchbase_index_path }}"
    when: couchbase_major_version.stdout > "2"
    register: couchbase_init_node
    failed_when:
      - "couchbase_init_node.stdout != 'SUCCESS: set hostname for ' ~ ansible_fqdn"
      - "couchbase_init_node.stdout != 'ERROR: unable to set hostname for ' ~ ansible_fqdn ~ ' (400) Bad Request\n[\"Renaming is disallowed for nodes that are already part of a cluster\"]'"
