---
  - name: Wait for Admin service
    wait_for:
      port: "{{ couchbase_admin_port }}"
      delay: 2

  - name: Check if cluster already configured
    shell: "{{ couchbase_bin_path }}/couchbase-cli server-list -c {{ ansible_fqdn }}:{{ couchbase_admin_port }} --user={{ couchbase_admin_username }} --password={{ couchbase_admin_password }} | wc -l"
    register: couchbase_check_cluster_node

  - name: Configure cluster settings (version < 4)
    shell: "{{ couchbase_bin_path }}/couchbase-cli cluster-init -c {{ couchbase_primary_node }}:{{ couchbase_admin_port }} --user={{ couchbase_admin_username }} --password={{ couchbase_admin_password }} --cluster-init-username={{ couchbase_admin_username }} --cluster-init-password={{ couchbase_admin_password }} --cluster-init-port={{ couchbase_admin_port }} --cluster-init-ramsize={{ couchbase_memory }}"
    when: 
      - couchbase_major_version.stdout < "4"
      - couchbase_check_cluster_node.stdout == "1"
    register: couchbase_configure_cluster

  - name: Configure cluster settings (version >= 4)
    shell: "{{ couchbase_bin_path }}/couchbase-cli cluster-init -c {{ couchbase_primary_node }}:{{ couchbase_admin_port }} --user={{ couchbase_admin_username }} --password={{ couchbase_admin_password }} --cluster-init-username={{ couchbase_admin_username }} --cluster-init-password={{ couchbase_admin_password }} --cluster-init-port={{ couchbase_admin_port }} --cluster-init-ramsize={{ couchbase_memory }} --services={{ couchbase_node_services }}"
    when:
      - couchbase_major_version.stdout >= "4"
      - couchbase_check_cluster_node.stdout == "1"
    register: couchbase_configure_cluster

  - name: Join additional cluster nodes (version < 4)
    shell: "{{ couchbase_bin_path }}/couchbase-cli server-add -c {{ couchbase_primary_node }}:{{ couchbase_admin_port }} --user={{ couchbase_admin_username }} --password={{ couchbase_admin_password }} --server-add={{ hostvars[item[0]]['inventory_hostname'] }}:{{ couchbase_admin_port }} --server-add-username={{ couchbase_admin_username }} --server-add-password={{ couchbase_admin_password }}"
    with_items: "{{ groups['couchbase-additional'] }}"
    when:
      - couchbase_major_version.stdout < "4"
      - couchbase_check_cluster_node.stdout == "1"

  - name: Join additional cluster nodes (version >= 4)
    shell: "{{ couchbase_bin_path }}/couchbase-cli server-add -c {{ couchbase_primary_node }}:{{ couchbase_admin_port }} --user={{ couchbase_admin_username }} --password={{ couchbase_admin_password }} --server-add={{ hostvars[[item][0]]['inventory_hostname'] }}:{{ couchbase_admin_port }} --server-add-username={{ couchbase_admin_username }} --server-add-password={{ couchbase_admin_password }} --services={{ couchbase_node_services }}"
    with_items: "{{ groups['couchbase-additional'] }}"
    when:
      - couchbase_major_version.stdout >= "4"
      - couchbase_check_cluster_node.stdout == "1"

  - name: Rebalance cluster
    shell: "{{ couchbase_bin_path }}/couchbase-cli rebalance -c {{ couchbase_primary_node }}:{{ couchbase_admin_port }} --user={{ couchbase_admin_username }} --password={{ couchbase_admin_password }}"
    when: couchbase_check_cluster_node.stdout == "1"
