---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- include_tasks: couchbase_pre.yml
- include_tasks: couchbase_install.yml

- block: # Config Nexus
  - include_tasks: couchbase_post.yml
  tags:
    - couchbase-config
